language: node_js
node_js:
  - '11'
install:
  - yarn install
script:
  - yarn ci
env:
  - CODECLIMATE_REPO_TOKEN=8c17e694e9b7e5110a57af7e8f780b9ebdcd4d3859f628cc6cd6d3d730194890
after_script:
  - ./node_modules/.bin/codeclimate-test-reporter < coverage/lcov.info
